package com.github.mafelp.accounts;

import org.bukkit.entity.Player;
import org.javacord.api.entity.user.User;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Random;

/**
 * The class that handles linking on the Discord side of things.
 */
public class DiscordLinker {
    /**
     * The Map that contains as key the {@link Player} that created the link token and as the Value an {@link Integer}
     * between 100,000 and 999,999.
     */
    private static final Map<User, Integer> linkableAccounts = new HashMap<>();

    /**
     * Checks the {@link DiscordLinker#linkableAccounts} list, if the {@link User} already has a linking token and
     * if so, it returns the token from this map. If the user does not have a token yet, it creates one and
     * adds it to the {@link DiscordLinker#linkableAccounts} map, associated with the user.
     * @param user The user to get the Linking Token from.
     * @return The Token used to link the account in minecraft.
     */
    public static int getLinkToken(User user) {
        if (linkableAccounts.containsKey(user))
            return linkableAccounts.get(user);
        else {
            int linkID = randomLinkToken();
            linkableAccounts.put(user, linkID);
            return linkID;
        }
    }

    /**
     * The method used to create a linked {@link Account} with a discord user and the linking ID of a minecraft Player.
     * The linkID has to be generated by {@link DiscordLinker#getLinkToken(User)}.
     * @param player The minecraft {@link Player} to link the discord {@link User} to.
     * @param linkID The ID used for finding the correct discord {@link User}.
     * @return If the ID is a valid token, it returns the newly {@link Account}, which was added to the list of accounts.
     *      If the ID is invalid, it returns an empty account.
     */
    public static Optional<Account> linkToMinecraft(Player player, int linkID) {
        // Iterates over all the discord accounts
        for (User u: linkableAccounts.keySet()) {
            // if the linkID passed in matches the id generated in the DiscordLinker#getLinkToken function,
            // it would create a new Account with the player and the User and adds this account.
            if (linkableAccounts.get(u) == linkID) {
                Account account = new Account(u, player);

                AccountManager.addAccount(account);

                //removes the current linkID from the map, so the link id would be freed again.
                linkableAccounts.remove(u);

                return Optional.of(account);
            }
        }

        // If the linkID matches none of the ID in the linkableAccounts ID, return noting.
        return Optional.empty();
    }

    /**
     * The method used to create a new Linking token, aka a {@link Random}, 6-Digit number, that is not already
     * in the linkableAccounts list. This prevents two users from having the same linking token.
     * @return a random linking token.
     */
    private static int randomLinkToken() {
        Random random = new Random();
        int r;
        do {
            r = random.nextInt(899_999) + 100_000;
        } while (linkableAccounts.containsValue(r));

        return r;
    }
}
