version: 2
registries:
  maven-spigot:
    type: maven-repository
    url: https://hub.spigotmc.org/nexus/content/repositories/snapshots/
  maven-sonatype:
    type: maven-repository
    url: https://oss.sonatype.org/content/groups/public/

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "MaFeLP"
    reviewers:
      - "MaFeLP"
    commit-message:
      prefix: "Maven"
      include: "scope"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "MaFeLP"
    reviewers:
      - "MaFeLP"
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"
    labels:
      - "dependencies"
