theme: jekyll-theme-cayman
show_downloads: false
include:
  - configuration.md
  - assets/
  - installation.md
  - building-from-source.md
  - get-channel-ID.md
  - invite-bot.md
  - create-admin-role.md
  - commands/
markdown: kramdown
