# Configuration file for plugin MCDC
# Author: MaFeLP (https://github.com/MaFeLP/MCDC/)

# if the message should be shortened
# Allowed values: <true|false>
useShortMessageFormat: false

# the prefix displayed in the console before logs and in
# Allowed values: any String
pluginPrefix: '§8[§6MCDC§8]§0: §r'

# The name of the server displayed in discord messages
# Allowed values: any string
serverName: 'A Minecraft Server'

# If additional information should be displayed.
# Allowed values: <true|false>
debug: false

# The Token used to create your bot instance
# Allowed values: any String
apiToken: 'Your API Token goes here!'

# The String used before commands in the discord channels
# Allowed values: any String
discordCommandPrefix: '.'

# Selects if messages that are commands should be deleted after execution.
# Allowed values: <true|false>
deleteDiscordCommandMessages: false

# Discord Channel IDs to broadcast messages to.
channelIDs:
  - 1234

# Discord Role IDs that hav permission to use slash commands
roleIDs:
  - 1234

# Enables accounts and linking.
# Allowed values <true|false>
enableLinking: true

# Allow players to list all the accounts.
# Allowed values <true|false>
allowListAllAccounts: true

# Decides, if the config value 'serverName' should be displayed in the footer of discord messages.
# Allowed values <true|false>
showFooterInMessages: true

# The value that should be displayed below the name
activity:
  # If the bot should have an activity.
  enabled: true
  # The type of the message, aka. the first word:
  # can be set to custom, competing, listening, watching, streaming or playing
  type: listening
  # The text that should be displayed.
  message: "your messages 👀"

# If the bot should send a message to the listening channels, if a command was executed by ...
sendCommandToDiscord:
  # ... a player.
  player: false
  # ... the server.
  server: false

# Server events that will trigger a message in discord
events:
  - JoinEvent # When a player joins the Server
  - LeaveEvent # When a player leaves the Server
  - PlayerAdvancementEvent # When a player gets a new Advancement
  - PlayerDeathEvent # When a Player dies
  - ServerStartupEvent # When the minecraft server starts
  - ServerShutdownEvent # When the minecraft server stops

# Permission section for setting permission levels
permission:
  # The permissions on linking and editing accounts.
  accountEdit:
    # The OP level needed to remove accounts of players.
    level: 3
    # A list of UUIDs of Players who have a wildcard to use this command.
    allowedUserUUIDs:
      - a unique ID

  # Permission for minecraft command /config
  configEdit:
    # Required OP level
    level: 3
    # A list of UUIDs of Players who have a wildcard to use this command.
    allowedUserUUIDs:
    - a unique ID


  # Discord Server Admins are allowed to create Channels and Roles
  discordServerAdmin:
    # A list of discord IDs of users who have a wildcard to use this command
    allowedUserIDs:
    - 1234

  # Discord Bot admins, use cases may follow.
  discordBotAdmin:
    # A list of authorised bot users.
    allowedUserIDs:
      - 1234

# If the command parser should treat \ as a normal character
# Allowed values: <true|false>
saveEscapeCharacterInConfig: true